# Generated by Django 4.1 on 2022-08-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='DetectionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'detection_types',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('cam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.camera')),
                ('detection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.detectiontype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.state')),
            ],
            options={
                'db_table': 'detections',
            },
        ),
    ]
