# Generated by Django 4.1 on 2022-08-30 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'detection_types',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_state', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('progress', models.IntegerField(null=True)),
                ('serial_number', models.CharField(max_length=45)),
                ('datetime', models.DateTimeField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection', to='area.area')),
                ('detection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection', to='detection.detectiontype')),
            ],
            options={
                'db_table': 'detection',
            },
        ),
    ]
