# Generated by Django 4.1 on 2022-08-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cam_latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cam_longitude', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
    ]
