# Generated by Django 4.1 on 2022-08-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='owner',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='image',
        ),
    ]
