# Generated by Django 4.1 on 2022-08-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detections', '0001_initial'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=45)),
                ('serial_number', models.CharField(max_length=45)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='areas.area')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='detections.detectiontype')),
            ],
            options={
                'db_table': 'equipments',
            },
        ),
    ]
