# Generated by Django 4.1 on 2022-08-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detections', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment'),
        ),
        migrations.AddField(
            model_name='detection',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detections.state'),
        ),
    ]
