# Generated by Django 4.1 on 2022-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0003_rename_name_state_equipment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='serial_number',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
