# Generated by Django 4.1 on 2022-08-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0004_detection_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='progress',
            field=models.IntegerField(null=True),
        ),
    ]
